# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'initial-page'
  link: '/initial-page'
# - label: Usage
#   items:
#     - label: 'Creating docs'
#       link: '/usage/creating-docs'
#     - label: 'Navigation'
#       link: '/usage/navigation'
#     - label: 'Shadowing'
#       link: '/usage/shadowing'
